### ISSUE TITLE
Build failed after upgrading version from 11.0.0 to 13.0.0

### ISSUE THREAD

**Issue by sachinrana135** [graphql-java-kickstart/graphql-java-tools#727] opened 2023-01-02 15:31 UTC
### Expected behavior

Build should pass.

### Actual behavior

After upgrading **com.graphql-java-kickstart:graphql-spring-boot-starter** version from 11.0.0 to 13.0.0 and **com.apollographql.federation:federation-graphql-java-support** from 2.0.0 to 2.1.0, I am  getting below error.  I do not have any field with name 'FieldSet' in my graphql schema file.  Can someone help with this error.

> Caused by: graphql.kickstart.tools.SchemaError: Expected type 'FieldSet' to be a GraphQLInputType, but it wasn't!  Was a type only permitted for object types incorrectly used as an input type, or vice-versa?
> 	at graphql.kickstart.tools.SchemaParser.determineType(SchemaParser.kt:355) ~[graphql-java-tools-13.0.0.jar:na]
> 	at graphql.kickstart.tools.SchemaParser.determineInputType(SchemaParser.kt:373) ~[graphql-java-tools-13.0.0.jar:na]
> 	at graphql.kickstart.tools.SchemaParser.determineInputType(SchemaParser.kt:365) ~[graphql-java-tools-13.0.0.jar:na]
> 	at graphql.kickstart.tools.SchemaParser.createDirective(SchemaParser.kt:307) ~[graphql-java-tools-13.0.0.jar:na]
> 	at graphql.kickstart.tools.SchemaParser.parseSchemaObjects(SchemaParser.kt:83) ~[graphql-java-tools-13.0.0.jar:na]
> 	at com.gta.configurations.GraphQLJavaToolsConfiguration.schemaTransformer(GraphQLJavaToolsConfiguration.java:56) ~[classes/:na]
> 	at com.gta.configurations.GraphQLJavaToolsConfiguration$$EnhancerBySpringCGLIB$$dd4748b7.CGLIB$schemaTransformer$0(<generated>) ~[classes/:na]
> 	at com.gta.configurations.GraphQLJavaToolsConfiguration$$EnhancerBySpringCGLIB$$dd4748b7$$FastClassBySpringCGLIB$$868bf799.invoke(<generated>) ~[classes/:na]
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.18.jar:5.3.18]
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.18.jar:5.3.18]
> 	at com.gta.configurations.GraphQLJavaToolsConfiguration$$EnhancerBySpringCGLIB$$dd4748b7.schemaTransformer(<generated>) ~[classes/:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.18.jar:5.3.18]
> 	... 140 common frames omitted
> 
> org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat``

### Steps to reproduce the bug

1. ...
2. ...
3. ...

**Comment by anbusampath** [comment] 2023-01-03 19:59
May be related to this - [#664 ](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/664)

**Comment by oryan-block** [comment] 2023-09-20 20:42
Duplicate of #664 - should be fixed.

**Closed by oryan-block** 2023-09-20 20:42 UTC
Labels: bug
