### ISSUE TITLE
ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer when using Relay/SimpleListConnection

### ISSUE THREAD

**Issue by mxmlnglt** [graphql-java-kickstart/graphql-java-tools#351] opened 2020-01-15 08:44 UTC
A while ago, I opened an issue on https://github.com/graphql-java/graphql-java/issues/1680 about a `ClassCastException` occuring while using a default value in the context of Relay/SimpleListConnection.

By browsing the stacktrace, it seemed to me it was due to graphql-java, but the maintainer says it's not; seems like graphql-java-tools is sending the wrong type of value (a `BigInteger` instead of an `Integer`).

Can you have a look please?

**Comment by roblovelock** [comment] 2020-02-11 14:32
I am experiencing the same issue. I think it is the same as issue #344

**Comment by mxmlnglt** [comment] 2020-02-11 20:38
Exactly... I think I'm not keen enough on GraphQL to have been able to find it in the first place... Thanks for linking the issues.

**Comment by oryan-block** [comment] 2024-01-31 21:02
Seems to be a duplicate of https://github.com/graphql-java-kickstart/graphql-java-tools/issues/344

**Closed by oryan-block** 2024-01-31 21:02 UTC
Labels: bug
